### ISSUE TITLE
google calendar interface

### ISSUE THREAD

**Issue by sweenejo** [uhmasw/uhmasw.github.io#3]
In addition to the subscribe feature, what about incorporating a google calendar interface?

**Comment by sweenejo** [comment]
https://support.google.com/calendar/answer/41207?hl=en

**Comment by johnwoodill** [comment]
Great link!  I added a branch googlecal that adds a calendar to the index page.  We should probably format it and figure out how to show events -- i can't figure out how to show the events after they were added.

**Comment by johnwoodill** [comment]
I just pulled your code and it looks like the calendar is showing the events now.  We can add links within the page using <a name="anchor"></a> and reference them in google calendar as http://uhmasw.github.io/index.html#anchor.  This would be useful for each post using google calendar.  I've pushed this update to the branch

**Comment by sweenejo** [comment]
Great work.  That looks like the last piece of the puzzle.  So no we can add seminars to the R file, add them to the google calendar, and link the calendar to the seminar listing!  Sounds like we just need to draft and About section and news section, and get the subscription interface working.  If we can anchor the existing seminars, lets close this issue.  What'ya say?

**Comment by johnwoodill** [comment]
Yeah I think it is fine to close this after a merge to `master`. We should think about how to label the anchors so we can maintain all seminar links.  Something like `#authordate`? (e.g. jonathansweeney05092016).  This can transfer to an archive and label section later.

**Comment by johnwoodill** [comment]
We can use: `<a href="uhmasw.github.io/index.html#jonsweeney05092016">Link to seminar details</a>` within the google calendar page.  If someone clicks on the google calendar from the page they will be directed to the location on the page using `<a name="jonsweeney05092016"></a>`

**Comment by johnwoodill** [comment]
Merged branch `googlecal` to `master`.  Link is working now.  Delete branch?

**Comment by sweenejo** [comment]
Yeah lets delete branch.
